[package]
name = "MarvinDocs"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdbook = "0.4.36"
mdbook-toc = "0.14.2"
mdbook-catppuccin = "2.1.0"
