[package]
name = "MarvinDocs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdbook = "0.4.28"
mdbook-toc = "0.11.2"
mdbook-catppuccin = "0.2.0"
